# Config file for Git-Courseware

# Build settings - Do not change these settings
remote_theme: mjsamberg/git-courseware
plugins:
  - jekyll-feed

# Site information. Change the information after the first semicolon (:) and before the pound sign (#)
title: "VisSDK"
style: ncstate # Site theme - Current values are "ncstate" and "generic"
nav_showcourses: 1 # Set to 0 to show a "Courses" menu with a link to each course. Set to 1 to show each course in the navbar with a link to the units as a dropdown

#College/Org Information
org_name: University Libraries # Name of the organization. For the ncstate theme, this should be the college
org_url: https://www.lib.ncsu.edu/ # URL of the organization
unit_name_long: "University Libraries Research Engagement" # Name of the department or unit within the organization
unit_url: https://www.lib.ncsu.edu/ # URL of the departmental unit
address: "<br/> <br/>library_hightechspaces@ncsu.edu<br/><br/>D. H. Hill Jr. Library<br/>2 Broughton Drive<br/>Campus Box 7111<br/>Raleigh, NC 27695-7111" # Physical Address
phone: "919-513-0086" # Change to your phone number
email: "library_hightechspaces@ncsu.edu" # Change to your email address 

#Social media links
#github_url: "https://github.com/mjsamberg/git-courseware-template" #URL of the GitHub Repository for people to fork
#facebook_username: 
#twitter_username: 
#github_username:  



# A list of the pages to display in the navigation bar and in the footer. Use "absolute: true" for external links
header_pages:
  - title: "Home"
    url: "/"

footer_pages: 
  - title: Home
    url: /